### ISSUE TITLE
PdoMenu: tplInner fenom parser bug

### ISSUE THREAD

**Issue by faitno** [modx-pro/pdoTools#149]
in snippet PdoMenu, I have change chank tplInner for this:

```
chunk "tplInner":
<ul>{$wrapper}
<li><a href="{{+link}}">{{+menutitle}}</a></li>
</ul>
```

And all work perfectly.
But, if I use fenom syntaxis:

```
chunk "tplInner":
<ul>{$wrapper}
<li><a href="{$link}">{$menutitle}</a></li>
</ul>
```

It not show placeholders {$link} and {$menutitle}.

**Comment by bezumkin** [comment]
You should not use
`<li><a href="{$link}">{$menutitle}</a></li>`
in tplInner because it is a wrapper for inner links. By default, [it is equal to tplOuter](https://github.com/bezumkin/pdoTools/blob/b20b63288e4b5feaebcb1b6ef88b9c60e64854b0/core/components/pdotools/model/pdotools/pdomenu.class.php#L44-L46).

It is not contains any own links, [here you can see all placeholders for tplInner](https://github.com/bezumkin/pdoTools/blob/b20b63288e4b5feaebcb1b6ef88b9c60e64854b0/core/components/pdotools/model/pdotools/pdomenu.class.php#L163-L167).

But why it works with MODX syntax and didn`t works with Fenom? It a simple - MODX leaves unprocessed tags and they are replaced to data from previous row. So, you just see duplicates with MODX:
[![](https://file.modx.pro/files/7/3/9/739f4c8cd9ee26c319b612bf5ad201bes.jpg)](https://file.modx.pro/files/7/3/9/739f4c8cd9ee26c319b612bf5ad201be.png) 

and empty row with Fenom:
[![](https://file.modx.pro/files/a/a/e/aaed32ace05ad0ff367f31a877d2f5bas.jpg)](https://file.modx.pro/files/a/a/e/aaed32ace05ad0ff367f31a877d2f5ba.png)

So, this is not an error, you just use wrong placeholders for tplInner chunk
